### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by NanoAi** [LuaTenshi/GmodHNVTekken#1]
### --- MODELS ---
- [ ] Hood 1  -  Standard (Hood Up)
- [ ] Hood 2  -  Hood Down
----
- [ ] Shoes 1  -  Standard (Shoes On)
- [ ] Shoes 2  -  Shoes Off
----
- [ ] Scarf 1  -  Standard (Scarf On)
- [ ] Scarf 2  -  Scarf Off
----
- [ ] Socks 1  -  Standard (Socks On)
- [ ] Socks 2  -  Socks Off
----
### --- TEXTURES ---
- [ ] Suit 1  -  Standard (Brown)
- [ ] Suit 2  -  Black Bear
- [ ] Suit 3  -  Polar Bear
- [ ] Suit 4  -  Panda Bear
- [ ] Suit 5  -  Pink Bear
----
- [ ] Scarf 1  -  Stadard (Red)
- [ ] Scarf 2  -  Blue
- [ ] Scarf 3  -  White (Black Lines)
- [ ] Scarf 4  -  Black (White Lines)
- [ ] Scarf 5  -  Green
----
- [ ] Socks 1  -  Standard (Dark Brown)
- [ ] Socks 2  -  Black
- [ ] Socks 3  -  White
- [ ] Socks 4  -  Pink
- [ ] Socks 5  -  None (Hide by matching skin?)
----
### ??? OPTIONAL ???
* Should we have a bear suit off option?
* I would like to have various facial expressions, but is it worth it?
* Should there be stenciles like a heart over an eye for "Pink Bear" or a black panda like spot on "Panda Bear"?
* ^ Can we make those stenciles optional?
